// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbdjidycqfcvjthrhgag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZGppZHljcWZjdmp0aHJoZ2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzU4NzgsImV4cCI6MjA1MzgxMTg3OH0.NFeZfUEa9erApbWXzMdshvwP7XDMlU5RPsEf8WQmd7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);